import 'bootstrap-icons/font/boostrap-icons.css';
import 'bootstrap/dist/css/boostrap.css';
import 'aos/dist/aos/css';
import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";
import "./variables.css";

const ebGaramond = EB_Garamond({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Digital News App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.className}`}>
        {children}
      </body>
    </html>
  );
}
